### ISSUE TITLE
is development still happening here?

### ISSUE THREAD

**Issue by alphashuro** [eristoddle/zen-notebook#3]
I really like this app but I tried it last year and I was hoping to see some of the bugs fixed and features added by now, I must say I'm a bit disappointed to see that there has been no commit since then :(

**Comment by eristoddle** [comment]
Yeah, I do use this now. I plan on upgrading to using angular2/ionic2 and electron instead of node webkit for preparation to build mobile apps also. Development will continue. I just ran into a time crunch. Thanks though. I haven't had any feedback until I saw this. It is good to know other people like it too. It get's me motivated to get more time to work on it.

**Comment by alphashuro** [comment]
I have used ionic 2 and angular 2 and honestly I would not recommend that stack. Ionic was a good idea but Angular is its pitfall; you will have a much better experience with React or Vanilla.
